"""Text strings for Sudoku."""

OK = 'OK'
EXIT = 'Exit'
QUIT = 'Quit'
CLOSE = 'Close'
COPY = 'Copy'
EVENT = 'Event'
SAVE = 'Save'
NEW = 'New'
OPEN = 'Open'
EDIT = 'Edit'
DELETE = 'Delete'
ACCEPT = 'Accept'
SELECT = 'Select'
CONFIG = 'Preferences'
ELLIPSIS = ' ...'
LAUNCH = 'Launch'
DELETE_RECORD = 'Are you sure you wish to delete this record?'
DELETE_THESE_ITEMS = 'Are you sure you want to delete these item(s)?'
DELETE_ITEM = 'Are you sure you wish to delete this item?'
